### ISSUE TITLE
Reuse Guzzle Client

### ISSUE THREAD

**Issue by jeremeamia** [kitetail/zttp#14]
Instead of creating a new instance of a Guzzle client for each request, you should have a shared/singleton instance that you reuse. This would reuse the underlying cURL handle as well, which is an optimization if you end up doing more than one request to the same host.

**Comment by adamwathan** [comment]
Singleton! I like the sounds of that, thanks for the tip @jeremeamia and thanks for your great work on Guzzle 💪🏻
