### ISSUE TITLE
Trying to understand the tap function

### ISSUE THREAD

**Issue by Fuitad** [kitetail/zttp#17]
Hey there. I hope you'll excuse me for this non-issue but I was going thru the code after hearing you talk about it on the Full stack podcast and I can't quite understand what the tap function is supposed to do. Would you mind sparing a second to explain it?

Thanks! :D

**Comment by adamwathan** [comment]
Haha yeah sure! It's really just an alternative to a temporary variable in most cases, mostly just a superficial style preference.

All it does is take any value as it's first argument, pass that value into the callback provided as the second argument so you can do whatever you need to do with that value, and then return that same value again.

Here's an example of some code you could write without `tap`:

```php
public function createAdmin()
{
    $user = new User;
    $user->isAdmin = true;
    return $user;
}
```

...and here's what it would look like with `tap`:

```php
public function createAdmin()
{
    return tap(new User, function ($user) {
        $user->isAdmin = true;
    });
}
```

Again, it's mostly a superficial difference, but something about the `tap` version feels "purer" to me in some way 😄

Hope that helps!

**Comment by Fuitad** [comment]
Thank you very much for taking the time to give this explanation. :)
