### ISSUE TITLE
How to send the original url?

### ISSUE THREAD

**Issue by yoolom** [kitetail/zttp#22]
example : Zttp::get('http://demo.com/sms?user=user&password=@123456');
the web server get full url is  'http://demo.com/sms?user=user&password=%40123456',
SMS server is a third-party server, so I can‘t use urldecode to modify parameters, how do I use Zttp to achieve the purpose

**Comment by adamwathan** [comment]
Hey @yoolom sorry I don't really understand your question.

If you send a request like `http://demo.com/sms?user=user&password=@123456`, the query parameters will be URL encoded. Are you asking for a way to try and make a request without URL encoding the query parameters? If so I'm not sure that's something that can be supported; that sounds like a bug on the third party server.

**Comment by faustbrian** [comment]
According to this commit https://github.com/guzzle/psr7/commit/962735c754f2a562a619b456a3aa4e614f0e5360 the @ should stay the same and not be encoded.

**Comment by jpuck** [comment]
[The specification][1] defines the `@` symbol as a `gen-delim` reserved character for use delimiting a resource location, in particular, the [User Information component][2] of a URI separating username from hostname in a basic auth request `https://username:password@example.com` or `mailto:username@example.com`

[reserved characters][3]

> **If** data for a URI component would conflict with a reserved
   character's purpose as a delimiter, then the conflicting data must be
   percent-encoded before the URI is formed.

If your password is `@123456` then a basic auth request must encode this as `https://user:%40123456@example.com`

However, considering the example does not use the `@` sign in a User Information component, but in the [query component][4] then I don't think it conflicts in this case.

> URI producing applications **should** percent-encode data octets that
   correspond to characters in the reserved set unless these characters
   are specifically allowed by the URI scheme to represent data in that
   component.

Although it's recommended to percent-encode the `@` even if it's not explicitly part of the conflict-able User Information component.

> If a reserved character is found in a URI component and
   no delimiting role is known for that character, then it must be
   interpreted as representing the data octet corresponding to that
   character's encoding in US-ASCII.

The only reference I see for that character in the specification is within the User Information component, so it must be taken literally when used elsewhere.

IMO, although it seems technically correct to not percent-encode `@` in the query component, I agree with the specification that it *should* be percent-encoded.

[1]:https://tools.ietf.org/html/rfc3986
[2]:https://tools.ietf.org/html/rfc3986#section-3.2.1
[3]:https://tools.ietf.org/html/rfc3986#section-2.2
[4]:https://tools.ietf.org/html/rfc3986#section-3.4

**Comment by adamwathan** [comment]
No intention to ever deviate from whatever Guzzle happens to do with regards to this sort of thing, so going to close this. Recommend raising an issue on the Guzzle repo if it's decided it's actually a concern.
