### ISSUE TITLE
You're totally mad not following PSR-2 etc.

### ISSUE THREAD

**Issue by johnhunt** [kitetail/zttp#24]
See topic. This needs fixing if you want anyone to use this.

**Comment by reinink** [comment]
> if you want anyone to use this

IDK, seems to be off to a healthy start.

![image](https://user-images.githubusercontent.com/882133/27491521-c33e8522-5810-11e7-8429-a42da0ea8fdf.png)

**Comment by adamwathan** [comment]
Do the tests fail? If not there's nothing to "fix" unfortunately! 😄 Have a great weekend.
