### ISSUE TITLE
ZttpRequest constructor has more than one expression

### ISSUE THREAD

**Issue by DASPRiD** [kitetail/zttp#25]
The ZttpRequest has more than one expression and thus violates the code style of this project.

**Comment by adamwathan** [comment]
Agreed this is disappointing, let's brainstorm together on ways to reduce it to one. Any ideas?

**Comment by DASPRiD** [comment]
Sure, that's easy :)

```php
    function __construct($client)
    {
        list($this->client, $this->bodyFormat, $this->options) = [
            $client,
            'json',
            ['http_errors' => false]
        ];
    }
```

**Comment by adamwathan** [comment]
Hahaha that's actually very clever! 😄 You have my respect 💪🏻

I think I will still make an exception for constructors, haha...
