### ISSUE TITLE
Spacing within tap() for readibility

### ISSUE THREAD

**Issue by valorin** [kitetail/zttp#26]
The one thing that has kept me from using `tap()` in a lot of situations is the sheer verbosity of callback definition, and the lack of spacing directly after it. 

Consider the following, where the logic `$this->bodyFormat = $format;` is lost within the tap function:

```
function bodyFormat($format)
{
    return tap($this, function ($request) use ($format) {
        $this->bodyFormat = $format;
    });
}
```

I wonder if this style would be nicer for tapped functions:

```
function bodyFormat($format) {
    return tap($this, function ($request) use ($format) 
    {
        $this->bodyFormat = $format;
    });
}
```

It's the same number of lines, but keeps the logic as the focus, and shifts the `tap()` to part of the function scaffolding.

**Comment by adamwathan** [comment]
Interesting idea! I think for now I'd prefer to keep following PSR-2's bracing style to keep things consistent, but thanks for the thoughtful suggestion regardless, I appreciate it!
