### ISSUE TITLE
Suggestion: add a small testserver

### ISSUE THREAD

**Issue by freekmurze** [kitetail/zttp#3]
The idea of using a real server to run the tests against is great.  But as it stands now there's a big downside: unless you share your value of `TEST_SERVER_URL` contributors must built up their own testserver with the expected endpoints and responses to test the package locally.

My suggestion is that you include a small node base server to the tests. 

An example of such as server can be found in [the tests of spatie/laravel-uptime-monitor](https://github.com/spatie/laravel-uptime-monitor/tree/master/tests/server).  In those tests we added some methods to let our server respond what we want. To test `zttp` the test server would only contain some hard coded endpoints.

Downsides:
- you have to start up that node server before running the tests

Upsides:
- no real world testserver needed
- it's still an end to end test, incompatible changes in Guzzle will be catched
- contributors can run tests locally
- tests can be run even when not connected to the internet

In case you were wondering Travis can also [use that node server](https://github.com/spatie/laravel-uptime-monitor/blob/master/.travis.yml#L18).

If you're open for this I can whip up a PR that adds a testserver to the package.

**Comment by adamwathan** [comment]
There actually is a test server! 

https://github.com/kitetail/zttp/tree/master/tests/server

It's a tiny Lumen app 👍🏻 So to run the tests you just need to run something like:

```bash
# In one terminal
php -S localhost:9000 -t ./tests/server/public

# In another terminal
TEST_SERVER_URL=http://localhost:9000 phpunit
```

...or add a nice start script that checks for Travis like you guys did with the node one 👍🏻

**Comment by freekmurze** [comment]
Totally missed that server, lol. Nice :-)
