### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by devronhansen** [kitetail/zttp#53]
Hey,
i most likely missed something obvious here, but when i clone the repo, run composer install and composer test phpunit gets stuck.

Logs:

[2017-10-03 16:09:01] lumen.ERROR: Illuminate\Container\EntryNotFoundException in /Users/ronhansen/code/SideProjects/zttp/vendor/illuminate/container/Container.php:598
Stack trace:
#0 /Users/ronhansen/code/SideProjects/zttp/tests/server/public/index.php(21): Illuminate\Container\Container->get('/get', Object(Closure))
#1 {main}

Thank you for any help

**Comment by adamwathan** [comment]
Good catch, looks like some breaking changes in Lumen 5.5 are the culprit. Going to make some changes and lock down our dependencies a bit tighter.
