### ISSUE TITLE
How to post json?

### ISSUE THREAD

**Issue by endingman** [kitetail/zttp#57]
post json like this in postman:
![qq 20180117144924](https://user-images.githubusercontent.com/16915802/35029535-535f00b8-fb96-11e7-9492-7775b9f80148.png)

**Comment by bastien-phi** [comment]
I'm quite sure doing 
```
Zttp::post($url,['offest'=>0,'limit'=>10])
```
works as data are sent as Json by default.
If you want to explicit the fact that the data are sent as json, you can do
```
Zttp::asJson()->post($url,['offest'=>0,'limit'=>10])
```
Is it what you need ?

**Comment by endingman** [comment]
@bastien-phi 
It does not work. I use guzzle/guzzle instead: 
 ```
$client   = $this->getClient();
        $response = $client->request('POST', self::API_LIST . '?access_token=' . $token['access_token'], [
            'headers' => [
                'Content-Type' => 'application/json;charset=utf-8',
                'Accept'       => 'application/json',
            ],
            'body'    => json_encode(['offset' => self::$begin, 'limit' => self::$limit]),
        ]);

        return $response->getBody()->getContents();
```
It looks like need a 'body' parm.
