### ISSUE TITLE
Are you planning to support it? (add docs/etc.)

### ISSUE THREAD

**Issue by Denis4yk** [kitetail/zttp#64]
Hello, Adam. If you are busy on tailwind, please, let users of this package know :)

**Comment by adamwathan** [comment]
I still use the package on all of my own projects so it's still active 👍 Haven't specifically blocked out time to put together proper docs or anything though.

As with all free open source work, use it if you like it and it meets your needs, but try not to have any expectations that someone else will support and maintain it for you forever for free. Even if I did stop actively using this library anyone is free to fork and continue developing it themselves 👍
