### ISSUE TITLE
Add visible keywords for all methods

### ISSUE THREAD

**Issue by peter279k** [kitetail/zttp#71]
As title, I think it should add the visible keywords for all methods.

Such as `public` and `private`.

It can help use to know methods easily.

**Comment by adamwathan** [comment]
> *This library does not use type-hints, follow PSR-2, or apply most other "best practices."*
>
> This is intentional, and mostly just to make life a little more fun. Life's too short to take everything so seriously.

https://github.com/kitetail/zttp/blob/master/CONTRIBUTING.md
