### ISSUE TITLE
Ability to set base url

### ISSUE THREAD

**Issue by mehrancodes** [kitetail/zttp#74]
Any idea?

**Comment by adamwathan** [comment]
No plans to do this as I'd like the library to remain stateless, sorry. Best bet is to create a little function in your own project that adds your base URL to whatever URL you pass, like:

```php
Zttp::post(api_url('/whatever'), ...)

function api_url($url) {
  return 'https://my-base-url.com' . $url;
}
```

**Comment by mehrancodes** [comment]
Or maybe I should create another wrapper around zttp :smiley: 
BTW thanks :+1:
